### PR TITLE
puppet-dnsquery: Add option to specify target DNS server

### PR DESCRIPTION
**Pull request by wstiern**

### CODE REVIEW

**Comment by wstiern** [comment]
Been using this to talk to Consul for a while now, works like a champ. :)

**Comment by dalen** [comment]
Hi, thanks for the contribution.

I wonder if it isn't better to accept an options hash though and send that to `Resolv::DNS.new` (after converting the keys to symbols as they will be strings in puppet).
It seems like there will be a bit of an explosion of positional arguments otherwise, and sometimes you might want to for example supply `search` but not `nameserver`.

Also, the `:arity` on the functions need to be updated (to -2), otherwise this should at least fail the arity check in Puppet 3.1.0+.

**Comment by hvhaugwitz** [comment]
What is the state of this pull request?

**Comment by b4ldr** [comment]
closing this, i think it is useful however the api has changed significantly since the original patch and would require a re-write

**Comment by b4ldr** [comment]
FYI i have added a new PR with similar functionality in #129 feedback most welcom

**Pull request closed without merging**
